---

galaxy_info:
  author: zenoamaro
  description: A role to install and configure Supervisord
  version: 0.3.0
  license: MIT
  min_ansible_version: 1.4

  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty

  categories:
    - monitoring

dependencies: []
