---
- name: ensure admin group
  group: name=admin state=present

- name: ensure ansible user
  user: name=ansible groups=sudo,admin shell=/bin/bash generate_ssh_key=yes

- name: ensure sudoers config
  copy: src=sudoers dest=/etc/sudoers owner=root mode=440

- name: ensure authorized_keys
  copy: src=authorized_keys dest=/home/ansible/.ssh/authorized_keys owner=ansible mode=600

- name: install basic tools
  apt: pkg={{item}} state=present
  with_items:
    - curl

- name: create ~/.pip directory
  file: path=/root/.pip state=directory

- name: copy pip.conf
  copy: src=pip.conf dest=/root/.pip/pip.conf owner=root mode=0644

- name: Install pip
  shell: curl -sL https://github.com/pypa/pip/raw/develop/contrib/get-pip.py | python creates=/usr/local/bin/pip

# - include: dns.yml
#   when: not no_dns is defined
